In [57]:
import pandas as pd

In [58]:
pd.__version__

'2.3.1'

In [59]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv')

In [60]:
df.head()

,Laptop,Status,Brand,Model,CPU,RAM,Storage,Storage type,GPU,Screen,Touch,Final Price
0,ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...,New,Asus,ExpertBook,Intel Core i5,8,512,SSD,NaN,15.6,No,1009.00
1,Alurin Go Start Intel Celeron N4020/8GB/256GB ...,New,Alurin,Go,Intel Celeron,8,256,SSD,NaN,15.6,No,299.00
2,ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...,New,Asus,ExpertBook,Intel Core i3,8,256,SSD,NaN,15.6,No,789.00
3,MSI Katana GF66 12UC-082XES Intel Core i7-1270...,New,MSI,Katana,Intel Core i7,16,1000,SSD,RTX 3050,15.6,No,1199.00
4,HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...,New,HP,15S,Intel Core i5,16,512,SSD,NaN,15.6,No,669.01

In [61]:
# Number of records in df
df.shape

(2160, 12)

In [62]:
# Missin values in df
df.isna().sum()

Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             4
Touch              0
Final Price        0
dtype: int64

In [63]:
# df columns names

df.columns

Index(['Laptop', 'Status', 'Brand', 'Model', 'CPU', 'RAM', 'Storage',
       'Storage type', 'GPU', 'Screen', 'Touch', 'Final Price'],
      dtype='object')

In [64]:
# Max price for DELL PCs
df[['Brand','Final Price']][df.Brand =='Dell'].max()

Brand            Dell
Final Price    3936.0
dtype: object

In [65]:
# Screen columns median value
df.median(numeric_only=True)

RAM              16.000
Storage         512.000
Screen           15.600
Final Price    1031.945
dtype: float64

In [66]:
# Next, calculate the most frequent value of the same Screen column.
df['Screen'].value_counts().max()

np.int64(1009)

In [67]:
# Use fillna method to fill the missing values in Screen column with the most frequent value
#from the previous step.

df['Screen'].isna().sum() #Checking the number of missing values in column 'Screen'

np.int64(4)

In [68]:
df['Screen'].fillna(df['Screen'].value_counts().max(),inplace =True)

/tmp/ipykernel_22829/2657296977.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Screen'].fillna(df['Screen'].value_counts().max(),inplace =True)

In [69]:
df['Screen'].isna().sum()

np.int64(0)

In [70]:
df['Screen'].median(numeric_only=True)

np.float64(15.6)

In [79]:
for col in df.columns:
    print(col)

Laptop
Status
Brand
Model
CPU
RAM
Storage
Storage type
GPU
Screen
Touch
Final Price

In [82]:
df.dtypes

Laptop           object
Status           object
Brand            object
Model            object
CPU              object
RAM               int64
Storage           int64
Storage type     object
GPU              object
Screen          float64
Touch            object
Final Price     float64
dtype: object

In [92]:
# Select all the "Innjoo" laptops from the dataset
df['Brand'][df['Brand']=='Innjoo']

1478    Innjoo
1479    Innjoo
1480    Innjoo
1481    Innjoo
1482    Innjoo
1483    Innjoo
Name: Brand, dtype: object

In [96]:
# Select only columns RAM, Storage, Screen.

df[['RAM','Storage','Screen']]

      RAM  Storage  Screen
0       8      512    15.6
1       8      256    15.6
2       8      256    15.6
3      16     1000    15.6
4      16      512    15.6
...   ...      ...     ...
2155   16     1000    17.3
2156   16     1000    17.3
2157   32     1000    17.3
2158   16     1000    13.4
2159   16      256    13.4

[2160 rows x 3 columns]

In [105]:
#Get the underlying NumPy array. Let's call it X.


import numpy as np # import numpy

X = np.array(df[['RAM','Storage','Screen']] )

In [106]:
X.ndim

2

In [122]:
# Compute matrix-matrix multiplication between the transpose of X and X.
# To get the transpose, use X.T. Let's call the result XTX.

XTX  = np.dot(X.T,X)

In [126]:
def is_square_numpy_matrix(matrix):
    """Take a matrix as input ,checks if it is square and returns a True or False value"""
    if not isinstance(matrix, np.ndarray):
        raise TypeError("Input must be a NumPy array.")
    
    if matrix.ndim != 2:  # Ensure it's a 2D matrix
        return False
        
    rows, cols = matrix.shape
    return rows == cols

In [127]:
is_square_numpy_matrix(XTX)

True

In [128]:
#Compute the inverse of XTX.

XTX_inv = np.linalg.inv(XTX)

In [130]:
#Create an array y with values [1100, 1300, 800, 900, 1000, 1100].

y = np.array([1100, 1300, 800, 900, 1000, 1100])
y

array([1100, 1300,  800,  900, 1000, 1100])

In [148]:
# Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. 
#Call the result w.

XTX_inv_X= np.dot(X,XTX_inv)
XTX_inv_X.shape

(2160, 3)

In [154]:
XTX_inv_X[:6].shape

(6, 3)

In [157]:
np.dot(y.T,XTX_inv_X[:6])

array([0.02825021, 0.00263749, 0.0055302 ])

In [147]:
y.shape

(6,)