In [2]:
import pandas as pd
import numpy as np

In [3]:
pd.__version__

'2.3.1'

In [4]:
np.__version__

'2.3.1'

In [5]:
!wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv

--2025-09-17 00:46:01--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.108.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 874188 (854K) [text/plain]
Saving to: ‘car_fuel_efficiency.csv’

car_fuel_efficiency 100%[===================>] 853.70K  3.27MB/s    in 0.3s

2025-09-17 00:46:02 (3.27 MB/s) - ‘car_fuel_efficiency.csv’ saved [874188/874188]

In [4]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv')

In [5]:
df.head()

,Laptop,Status,Brand,Model,CPU,RAM,Storage,Storage type,GPU,Screen,Touch,Final Price
0,ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...,New,Asus,ExpertBook,Intel Core i5,8,512,SSD,NaN,15.6,No,1009.00
1,Alurin Go Start Intel Celeron N4020/8GB/256GB ...,New,Alurin,Go,Intel Celeron,8,256,SSD,NaN,15.6,No,299.00
2,ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...,New,Asus,ExpertBook,Intel Core i3,8,256,SSD,NaN,15.6,No,789.00
3,MSI Katana GF66 12UC-082XES Intel Core i7-1270...,New,MSI,Katana,Intel Core i7,16,1000,SSD,RTX 3050,15.6,No,1199.00
4,HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...,New,HP,15S,Intel Core i5,16,512,SSD,NaN,15.6,No,669.01

In [6]:
# Number of records in df
df.shape

(2160, 12)

In [7]:
# Missin values in df
df.isna().sum()

Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             4
Touch              0
Final Price        0
dtype: int64

In [8]:
# df columns names

df.columns

Index(['Laptop', 'Status', 'Brand', 'Model', 'CPU', 'RAM', 'Storage',
       'Storage type', 'GPU', 'Screen', 'Touch', 'Final Price'],
      dtype='object')

In [9]:
# Max price for DELL PCs
df[['Brand','Final Price']][df.Brand =='Dell'].max()

Brand            Dell
Final Price    3936.0
dtype: object

In [10]:
# Screen columns median value
df.median(numeric_only=True)

RAM              16.000
Storage         512.000
Screen           15.600
Final Price    1031.945
dtype: float64

In [11]:
# Next, calculate the most frequent value of the same Screen column.
df['Screen'].value_counts().max()

np.int64(1009)

In [12]:
# Use fillna method to fill the missing values in Screen column with the most frequent value
#from the previous step.

df['Screen'].isna().sum() #Checking the number of missing values in column 'Screen'

np.int64(4)

In [13]:
df['Screen'].fillna(df['Screen'].value_counts().max(),inplace =True)

/tmp/ipykernel_10664/2657296977.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Screen'].fillna(df['Screen'].value_counts().max(),inplace =True)

In [14]:
df['Screen'].isna().sum()

np.int64(0)

In [15]:
df['Screen'].median(numeric_only=True)

np.float64(15.6)

In [16]:
for col in df.columns:
    print(col)

Laptop
Status
Brand
Model
CPU
RAM
Storage
Storage type
GPU
Screen
Touch
Final Price

In [17]:
df.dtypes

Laptop           object
Status           object
Brand            object
Model            object
CPU              object
RAM               int64
Storage           int64
Storage type     object
GPU              object
Screen          float64
Touch            object
Final Price     float64
dtype: object

In [21]:
# Select all the "Innjoo" laptops from the dataset
df_inn = df[df['Brand']=='Innjoo']
df_inn.head()

,Laptop,Status,Brand,Model,CPU,RAM,Storage,Storage type,GPU,Screen,Touch,Final Price
1478,InnJoo Voom Excellence Intel Celeron N4020/8GB...,New,Innjoo,Voom,Intel Celeron,8,256,SSD,NaN,15.6,No,311.37
1479,InnJoo Voom Excellence Pro Intel Celeron N4020...,New,Innjoo,Voom,Intel Celeron,8,512,SSD,NaN,15.6,No,392.55
1480,Innjoo Voom Intel Celeron N3350/4GB/64GB eMMC/...,New,Innjoo,Voom,Intel Celeron,4,64,eMMC,NaN,14.1,No,251.40
1481,Innjoo Voom Laptop Max Intel Celeron N3350/6GB...,New,Innjoo,Voom,Intel Celeron,6,64,eMMC,NaN,14.1,No,383.61
1482,Innjoo Voom Laptop Pro Intel Celeron N3350/6GB...,New,Innjoo,Voom,Intel Celeron,6,128,SSD,NaN,14.1,No,317.02

In [22]:
# Select only columns RAM, Storage, Screen.

df_inn = df_inn[['RAM','Storage','Screen']]

In [24]:
#Get the underlying NumPy array. Let's call it X.


import numpy as np # import numpy

X = np.array(df_inn[['RAM','Storage','Screen']] )
X

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [25]:
X.ndim

2

In [26]:
# Compute matrix-matrix multiplication between the transpose of X and X.
# To get the transpose, use X.T. Let's call the result XTX.

XTX  = np.dot(X.T,X)

In [ ]:
# Due to the requirement of the next step-to compute the inverse of XTX. 
# Our numpy matrix must be square.
# Hence the function to check if the matrix is square below.
def is_square_numpy_matrix(matrix):
    """Takes a numpy matrix as input ,checks if it is square and returns a True or False value"""
    if not isinstance(matrix, np.ndarray): 
        raise TypeError("Input must be a NumPy array.")
    
    if matrix.ndim != 2:  # Ensure it's a 2D matrix
        return False
        
    rows, cols = matrix.shape
    return rows == cols

In [28]:
is_square_numpy_matrix(XTX)

True

In [29]:
#Compute the inverse of XTX.

XTX_inv = np.linalg.inv(XTX)

In [30]:
#Create an array y with values [1100, 1300, 800, 900, 1000, 1100].

y = np.array([1100, 1300, 800, 900, 1000, 1100])
y

array([1100, 1300,  800,  900, 1000, 1100])

In [31]:
# Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. 
#Call the result w.


w = np.dot(np.dot(XTX_inv,X.T),y)

In [ ]:
w

array([45.58076606,  0.42783519, 45.29127938])

Bad pipe message: %s [b' q=0.9, */*; q=0.8\r\nHost: localhost:34005\r\nUser-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) Appl', b'ebKit/605.1.15 (KHTML, like Gecko) Version/18.6 Safari/605.1.15\r\nAccept-Encoding: gzip, deflate, br\r', b'ccept-Lan', b'age: en-GB, en; q=0.9\r\nReferer: https://special-funicular-qvqjjxp4vrgc9q9w.github.dev/\r\nX-Request-ID: ', b'4fd38e62aea56f71a609e17aa22b07\r\nX-Real-IP: 10.241.0.36\r\nX-Forwarded-Port: 443\r\nX-Forwarded-Scheme:', b'ttps\r\nX-Original-URI: /\r\nX-Sche']
Bad pipe message: %s [b': https\r\nsec-fetch-site: same-site\r\npriority: u=0, i\r\nsec-fetch-mode: navigate\r\nsec-fetch-dest: document\r\nx-', b'iginal-proto: https\r\nX-Forwarded-Proto: https\r\nX-Forwarded-Host: special-funicular-qvqjjxp4vrgc9q9w-34005.app.']